export default {
  "login": "femmor",
  "id": 55207305,
  "node_id": "MDQ6VXNlcjU1MjA3MzA1",
  "avatar_url": "https://avatars.githubusercontent.com/u/55207305?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/femmor",
  "html_url": "https://github.com/femmor",
  "followers_url": "https://api.github.com/users/femmor/followers",
  "following_url": "https://api.github.com/users/femmor/following{/other_user}",
  "gists_url": "https://api.github.com/users/femmor/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/femmor/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/femmor/subscriptions",
  "organizations_url": "https://api.github.com/users/femmor/orgs",
  "repos_url": "https://api.github.com/users/femmor/repos",
  "events_url": "https://api.github.com/users/femmor/events{/privacy}",
  "received_events_url": "https://api.github.com/users/femmor/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Emmanuel Egomson",
  "company": null,
  "blog": "https://femmy.netlify.app",
  "location": "Oklahoma. USA",
  "email": null,
  "hireable": true,
  "bio": "React Developer",
  "twitter_username": null,
  "public_repos": 182,
  "public_gists": 0,
  "followers": 11,
  "following": 170,
  "created_at": "2019-09-11T18:05:38Z",
  "updated_at": "2021-06-20T15:36:13Z"
}
