export default [
  {
    "login": "Soldy",
    "id": 4786022,
    "node_id": "MDQ6VXNlcjQ3ODYwMjI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4786022?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Soldy",
    "html_url": "https://github.com/Soldy",
    "followers_url": "https://api.github.com/users/Soldy/followers",
    "following_url": "https://api.github.com/users/Soldy/following{/other_user}",
    "gists_url": "https://api.github.com/users/Soldy/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Soldy/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Soldy/subscriptions",
    "organizations_url": "https://api.github.com/users/Soldy/orgs",
    "repos_url": "https://api.github.com/users/Soldy/repos",
    "events_url": "https://api.github.com/users/Soldy/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Soldy/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "betocostadev",
    "id": 9079952,
    "node_id": "MDQ6VXNlcjkwNzk5NTI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9079952?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/betocostadev",
    "html_url": "https://github.com/betocostadev",
    "followers_url": "https://api.github.com/users/betocostadev/followers",
    "following_url": "https://api.github.com/users/betocostadev/following{/other_user}",
    "gists_url": "https://api.github.com/users/betocostadev/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/betocostadev/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/betocostadev/subscriptions",
    "organizations_url": "https://api.github.com/users/betocostadev/orgs",
    "repos_url": "https://api.github.com/users/betocostadev/repos",
    "events_url": "https://api.github.com/users/betocostadev/events{/privacy}",
    "received_events_url": "https://api.github.com/users/betocostadev/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "luchetu",
    "id": 11345077,
    "node_id": "MDQ6VXNlcjExMzQ1MDc3",
    "avatar_url": "https://avatars.githubusercontent.com/u/11345077?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/luchetu",
    "html_url": "https://github.com/luchetu",
    "followers_url": "https://api.github.com/users/luchetu/followers",
    "following_url": "https://api.github.com/users/luchetu/following{/other_user}",
    "gists_url": "https://api.github.com/users/luchetu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/luchetu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/luchetu/subscriptions",
    "organizations_url": "https://api.github.com/users/luchetu/orgs",
    "repos_url": "https://api.github.com/users/luchetu/repos",
    "events_url": "https://api.github.com/users/luchetu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/luchetu/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "arjun-choudhury",
    "id": 12852365,
    "node_id": "MDQ6VXNlcjEyODUyMzY1",
    "avatar_url": "https://avatars.githubusercontent.com/u/12852365?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/arjun-choudhury",
    "html_url": "https://github.com/arjun-choudhury",
    "followers_url": "https://api.github.com/users/arjun-choudhury/followers",
    "following_url": "https://api.github.com/users/arjun-choudhury/following{/other_user}",
    "gists_url": "https://api.github.com/users/arjun-choudhury/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/arjun-choudhury/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/arjun-choudhury/subscriptions",
    "organizations_url": "https://api.github.com/users/arjun-choudhury/orgs",
    "repos_url": "https://api.github.com/users/arjun-choudhury/repos",
    "events_url": "https://api.github.com/users/arjun-choudhury/events{/privacy}",
    "received_events_url": "https://api.github.com/users/arjun-choudhury/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "julioxavierr",
    "id": 14119096,
    "node_id": "MDQ6VXNlcjE0MTE5MDk2",
    "avatar_url": "https://avatars.githubusercontent.com/u/14119096?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/julioxavierr",
    "html_url": "https://github.com/julioxavierr",
    "followers_url": "https://api.github.com/users/julioxavierr/followers",
    "following_url": "https://api.github.com/users/julioxavierr/following{/other_user}",
    "gists_url": "https://api.github.com/users/julioxavierr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/julioxavierr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/julioxavierr/subscriptions",
    "organizations_url": "https://api.github.com/users/julioxavierr/orgs",
    "repos_url": "https://api.github.com/users/julioxavierr/repos",
    "events_url": "https://api.github.com/users/julioxavierr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/julioxavierr/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "nathansdev",
    "id": 14214630,
    "node_id": "MDQ6VXNlcjE0MjE0NjMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/14214630?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nathansdev",
    "html_url": "https://github.com/nathansdev",
    "followers_url": "https://api.github.com/users/nathansdev/followers",
    "following_url": "https://api.github.com/users/nathansdev/following{/other_user}",
    "gists_url": "https://api.github.com/users/nathansdev/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nathansdev/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nathansdev/subscriptions",
    "organizations_url": "https://api.github.com/users/nathansdev/orgs",
    "repos_url": "https://api.github.com/users/nathansdev/repos",
    "events_url": "https://api.github.com/users/nathansdev/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nathansdev/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "DevGbolade",
    "id": 36649630,
    "node_id": "MDQ6VXNlcjM2NjQ5NjMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/36649630?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DevGbolade",
    "html_url": "https://github.com/DevGbolade",
    "followers_url": "https://api.github.com/users/DevGbolade/followers",
    "following_url": "https://api.github.com/users/DevGbolade/following{/other_user}",
    "gists_url": "https://api.github.com/users/DevGbolade/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DevGbolade/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DevGbolade/subscriptions",
    "organizations_url": "https://api.github.com/users/DevGbolade/orgs",
    "repos_url": "https://api.github.com/users/DevGbolade/repos",
    "events_url": "https://api.github.com/users/DevGbolade/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DevGbolade/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "emexbazz",
    "id": 39973552,
    "node_id": "MDQ6VXNlcjM5OTczNTUy",
    "avatar_url": "https://avatars.githubusercontent.com/u/39973552?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/emexbazz",
    "html_url": "https://github.com/emexbazz",
    "followers_url": "https://api.github.com/users/emexbazz/followers",
    "following_url": "https://api.github.com/users/emexbazz/following{/other_user}",
    "gists_url": "https://api.github.com/users/emexbazz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/emexbazz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/emexbazz/subscriptions",
    "organizations_url": "https://api.github.com/users/emexbazz/orgs",
    "repos_url": "https://api.github.com/users/emexbazz/repos",
    "events_url": "https://api.github.com/users/emexbazz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/emexbazz/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jamesbarker585",
    "id": 42724731,
    "node_id": "MDQ6VXNlcjQyNzI0NzMx",
    "avatar_url": "https://avatars.githubusercontent.com/u/42724731?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jamesbarker585",
    "html_url": "https://github.com/jamesbarker585",
    "followers_url": "https://api.github.com/users/jamesbarker585/followers",
    "following_url": "https://api.github.com/users/jamesbarker585/following{/other_user}",
    "gists_url": "https://api.github.com/users/jamesbarker585/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jamesbarker585/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jamesbarker585/subscriptions",
    "organizations_url": "https://api.github.com/users/jamesbarker585/orgs",
    "repos_url": "https://api.github.com/users/jamesbarker585/repos",
    "events_url": "https://api.github.com/users/jamesbarker585/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jamesbarker585/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "aarveei",
    "id": 49666775,
    "node_id": "MDQ6VXNlcjQ5NjY2Nzc1",
    "avatar_url": "https://avatars.githubusercontent.com/u/49666775?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aarveei",
    "html_url": "https://github.com/aarveei",
    "followers_url": "https://api.github.com/users/aarveei/followers",
    "following_url": "https://api.github.com/users/aarveei/following{/other_user}",
    "gists_url": "https://api.github.com/users/aarveei/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aarveei/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aarveei/subscriptions",
    "organizations_url": "https://api.github.com/users/aarveei/orgs",
    "repos_url": "https://api.github.com/users/aarveei/repos",
    "events_url": "https://api.github.com/users/aarveei/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aarveei/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "devcoffee808",
    "id": 63756857,
    "node_id": "MDQ6VXNlcjYzNzU2ODU3",
    "avatar_url": "https://avatars.githubusercontent.com/u/63756857?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/devcoffee808",
    "html_url": "https://github.com/devcoffee808",
    "followers_url": "https://api.github.com/users/devcoffee808/followers",
    "following_url": "https://api.github.com/users/devcoffee808/following{/other_user}",
    "gists_url": "https://api.github.com/users/devcoffee808/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/devcoffee808/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/devcoffee808/subscriptions",
    "organizations_url": "https://api.github.com/users/devcoffee808/orgs",
    "repos_url": "https://api.github.com/users/devcoffee808/repos",
    "events_url": "https://api.github.com/users/devcoffee808/events{/privacy}",
    "received_events_url": "https://api.github.com/users/devcoffee808/received_events",
    "type": "User",
    "site_admin": false
  }
]